# Site settings
title: LEADSMITH
email: mark@theleadsmith.com
description: > # this means to ignore newlines until "baseurl:"
  PPC management and digital marketing made simple for your business. Get new leads and attract custmers with Google searches, Social Media campaigns, and advertisments.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:   

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"
